/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kmf_01;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author samod
 */
public class Login extends javax.swing.JFrame {
    DBConnect connection = new DBConnect("KMF_01");
    /**
     * Creates new form Test
     */
    public Login() {
        initComponents();
        
        role.add(rdDriver);
        role.add(rdStaffKantor);
        
        rdStaffKantor.setSelected(true);
        this.setResizable(false);
    }
    
    private void LoginUser() {
        try {
            DBConnect c = connection;
            c.stat = c.conn.createStatement();
            
            String sql;
            if(rdStaffKantor.isSelected()) {
                sql = "SELECT * FROM StaffKantor s JOIN Department d ON s.id_department = d.id_department"
                        + " WHERE username='" + txtUsername.getText() + "' AND password='" + txtPassword.getText() + "'";
            } else {
                sql = "SELECT * FROM Driver WHERE username='" + txtUsername.getText() + "' AND password='" + txtPassword.getText() + "'";
            }
            c.result = c.stat.executeQuery(sql);
            int count = 0;
            
            if(rdStaffKantor.isSelected()) {
                while(c.result.next()) {
                    count++;
                    KMFSession.setId_user(c.result.getString("id_staff"));
                    KMFSession.setUsername(c.result.getString("username"));
                    KMFSession.setNama_staff(c.result.getString("nama_staff"));
                    KMFSession.setRole(c.result.getString("nama_department"));
                    KMFSession.setKota(c.result.getString("kota"));
                }
            } else {
                while(c.result.next()) {
                    count++;
                    KMFSession.setId_user(c.result.getString("id_driver"));
                    KMFSession.setUsername(c.result.getString("username"));
                    KMFSession.setNama_staff(c.result.getString("nama_driver"));
                    KMFSession.setRole("Driver");
                    KMFSession.setKota(c.result.getString("kota"));
                }
            }
            
            if(count > 0) {
                JOptionPane.showMessageDialog(this, "Login berhasil", "Login berhasil", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                Template app = new Template();
                app.setNavigation(KMFSession.getNama_staff(), KMFSession.getRole());
                app.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Useraname atau password salah!", "Login gagal", JOptionPane.ERROR_MESSAGE);
            }
            
            c.stat.close();
            c.result.close();
        } catch(Exception e) {
            System.out.println("Terjadi error saat load data driver "  + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        role = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        rdStaffKantor = new javax.swing.JRadioButton();
        rdDriver = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(7026, 3218));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 577));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1020, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 550));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Silahkan login untuk melanjutkan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 136, 255));
        jLabel2.setText("SELAMAT DATANG DI PT. KMF");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kmf_01/images/Login.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, -1, -1));

        jPanel1.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kmf_01/images/person.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kmf_01/images/TopLogin.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 136, 255));
        jLabel1.setText("LOGIN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Password");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel4.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 200, 30));

        btnLogin.setBackground(new java.awt.Color(36, 136, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(36, 136, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 150, 40));

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 200, 30));

        rdStaffKantor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdStaffKantor.setText("Staff");
        rdStaffKantor.setOpaque(false);
        jPanel4.add(rdStaffKantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        rdDriver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdDriver.setText("Driver");
        rdDriver.setOpaque(false);
        jPanel4.add(rdDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jPanel1.add(jPanel4);

        jPanel3.add(jPanel1);

        getContentPane().add(jPanel3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        LoginUser();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LoginUser();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rdDriver;
    private javax.swing.JRadioButton rdStaffKantor;
    private javax.swing.ButtonGroup role;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
