/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kmf_01.content;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import kmf_01.DBConnect;

/**
 *
 * @author samod
 */
public class CekConnote extends javax.swing.JFrame {
    DBConnect connection = new DBConnect("KMF_01");
    DefaultTableModel model;

    
    /**
     * Creates new form Navbar
     */
    public CekConnote() {
        initComponents();
        
        FormLoad();
    }
    
    private void FormLoad() {
        model = new DefaultTableModel();
        tblHistory.setModel(model);
        addColumn();
    }
    
    private void addColumn() {
        model.addColumn("Tgl. History");
        model.addColumn("History");
    }
    
    private void loadData(String connote) {
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        SimpleDateFormat f2 = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        
        try {
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
            DBConnect c = connection;
            c.stat = c.conn.createStatement();
            String sql = "SELECT * FROM History h WHERE connote = '" + connote + "' ORDER BY tgl_history DESC";
            
            c.result = c.stat.executeQuery(sql);
            int count = 0;
            
            while(c.result.next()) {
                ResultSet r = c.result;
                Object obj[] = new Object[2];
                Date tgl = null;
                try {
                    tgl = f.parse(r.getString("tgl_history"));
                } catch(Exception e) {
                    System.out.println("Conversion date : " + e);
                }
                obj[0] = f2.format(tgl);
                obj[1] = r.getString("isi_history");
                
                model.addRow(obj);
                
                count++;
            }
            
            if(count == 0) {
                JOptionPane.showMessageDialog(Content, "Connote tidak ditemukan!");
            }
            
            c.stat.close();
            c.result.close();
        } catch(SQLException e) {
            System.out.println("Terjadi error saat load data paket "  + e);
        }
    }
    
    public JPanel getPanel() {
        return Panel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        PageTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtConnote = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        Data = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        lblHeader1 = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();
        lblHeader3 = new javax.swing.JLabel();
        lblHeader4 = new javax.swing.JLabel();
        lblHeader5 = new javax.swing.JLabel();
        Content1 = new javax.swing.JPanel();
        lblResi = new javax.swing.JLabel();
        lblJenisPengiriman = new javax.swing.JLabel();
        lblTglPengiriman = new javax.swing.JLabel();
        lblAsal = new javax.swing.JLabel();
        lblTujuan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        Header2 = new javax.swing.JPanel();
        lblHeader6 = new javax.swing.JLabel();
        lblHeader7 = new javax.swing.JLabel();
        Content2 = new javax.swing.JPanel();
        lblPengirim = new javax.swing.JLabel();
        lblPenerima = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(225, 228, 230));
        Panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        Panel.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                PanelHierarchyChanged(evt);
            }
        });
        Panel.setLayout(new javax.swing.BoxLayout(Panel, javax.swing.BoxLayout.Y_AXIS));

        PageTitle.setBackground(new java.awt.Color(225, 228, 230));
        PageTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        PageTitle.setMaximumSize(new java.awt.Dimension(32767, 70));
        PageTitle.setPreferredSize(new java.awt.Dimension(1136, 70));
        PageTitle.setLayout(new javax.swing.BoxLayout(PageTitle, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cek Connote");
        PageTitle.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(225, 228, 230));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        PageTitle.add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtConnote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConnote.setMinimumSize(new java.awt.Dimension(6, 30));
        txtConnote.setPreferredSize(new java.awt.Dimension(6, 30));
        txtConnote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConnoteKeyPressed(evt);
            }
        });
        jPanel1.add(txtConnote);

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.setMaximumSize(new java.awt.Dimension(51, 30));
        btnCari.setMinimumSize(new java.awt.Dimension(51, 30));
        btnCari.setPreferredSize(new java.awt.Dimension(51, 30));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari);

        PageTitle.add(jPanel1);

        Panel.add(PageTitle);

        Content.setBackground(new java.awt.Color(225, 228, 230));
        Content.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        Content.setPreferredSize(new java.awt.Dimension(1136, 400));
        Content.setLayout(new javax.swing.BoxLayout(Content, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel9.setPreferredSize(new java.awt.Dimension(686, 60));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        Header1.setMaximumSize(new java.awt.Dimension(32767, 60));
        Header1.setPreferredSize(new java.awt.Dimension(686, 60));
        Header1.setLayout(new java.awt.GridLayout(1, 5));

        lblHeader1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader1.setText("No. Resi");
        lblHeader1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Header1.add(lblHeader1);

        lblHeader2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader2.setText("Layanan");
        lblHeader2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Header1.add(lblHeader2);

        lblHeader3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader3.setText("Tgl. Pengiriman");
        lblHeader3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Header1.add(lblHeader3);

        lblHeader4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader4.setText("Asal");
        lblHeader4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Header1.add(lblHeader4);

        lblHeader5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader5.setText("Tujuan");
        lblHeader5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Header1.add(lblHeader5);

        jPanel9.add(Header1);

        Content1.setMaximumSize(new java.awt.Dimension(32767, 60));
        Content1.setPreferredSize(new java.awt.Dimension(686, 60));
        Content1.setLayout(new java.awt.GridLayout(1, 4));

        lblResi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResi.setText("-");
        lblResi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Content1.add(lblResi);

        lblJenisPengiriman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJenisPengiriman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJenisPengiriman.setText("-");
        lblJenisPengiriman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Content1.add(lblJenisPengiriman);

        lblTglPengiriman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTglPengiriman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTglPengiriman.setText("-");
        lblTglPengiriman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Content1.add(lblTglPengiriman);

        lblAsal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsal.setText("-");
        lblAsal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Content1.add(lblAsal);

        lblTujuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTujuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTujuan.setText("-");
        lblTujuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Content1.add(lblTujuan);

        jPanel9.add(Content1);

        jPanel4.add(jPanel9);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(1116, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1116, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3);

        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel10.setPreferredSize(new java.awt.Dimension(686, 60));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        Header2.setMaximumSize(new java.awt.Dimension(32767, 60));
        Header2.setPreferredSize(new java.awt.Dimension(686, 60));
        Header2.setLayout(new java.awt.GridLayout(1, 5));

        lblHeader6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader6.setText("Pengirim");
        lblHeader6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Header2.add(lblHeader6);

        lblHeader7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader7.setText("Penerima");
        lblHeader7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Header2.add(lblHeader7);

        jPanel10.add(Header2);

        Content2.setMaximumSize(new java.awt.Dimension(32767, 60));
        Content2.setPreferredSize(new java.awt.Dimension(686, 60));
        Content2.setLayout(new java.awt.GridLayout(1, 4));

        lblPengirim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPengirim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPengirim.setText("-");
        lblPengirim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Content2.add(lblPengirim);

        lblPenerima.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPenerima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPenerima.setText("-");
        lblPenerima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Content2.add(lblPenerima);

        jPanel10.add(Content2);

        jPanel4.add(jPanel10);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel5.setPreferredSize(new java.awt.Dimension(1116, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1116, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        tblHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHistory);

        jPanel6.add(jScrollPane1);

        jPanel4.add(jPanel6);

        javax.swing.GroupLayout DataLayout = new javax.swing.GroupLayout(Data);
        Data.setLayout(DataLayout);
        DataLayout.setHorizontalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DataLayout.setVerticalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        Content.add(Data);

        Panel.add(Content);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoryMouseClicked
        
    }//GEN-LAST:event_tblHistoryMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        loadData(txtConnote.getText());
        
        lblResi.setText(txtConnote.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtConnoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConnoteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loadData(txtConnote.getText());
        }
    }//GEN-LAST:event_txtConnoteKeyPressed

    private void PanelHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_PanelHierarchyChanged
        FormLoad();
    }//GEN-LAST:event_PanelHierarchyChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekConnote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekConnote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekConnote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekConnote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekConnote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Content1;
    private javax.swing.JPanel Content2;
    private javax.swing.JPanel Data;
    private javax.swing.JPanel Header1;
    private javax.swing.JPanel Header2;
    private javax.swing.JPanel PageTitle;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsal;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    private javax.swing.JLabel lblHeader3;
    private javax.swing.JLabel lblHeader4;
    private javax.swing.JLabel lblHeader5;
    private javax.swing.JLabel lblHeader6;
    private javax.swing.JLabel lblHeader7;
    private javax.swing.JLabel lblJenisPengiriman;
    private javax.swing.JLabel lblPenerima;
    private javax.swing.JLabel lblPengirim;
    private javax.swing.JLabel lblResi;
    private javax.swing.JLabel lblTglPengiriman;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTextField txtConnote;
    // End of variables declaration//GEN-END:variables
}
